quarkus:
  datasource:
    devservices:
      image-name: postgres:13.3
      port: 5433
  hibernate-orm:
    log:
      sql: true
    jdbc:
      timezone: Asia/Tokyo
  flyway:
    migrate-at-start: true
  resteasy:
    path: /api/media

"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://${db-host}:5432/${db-name}
      username: ${db-user}
      password: ${db-pass}

"%dev":
  quarkus:
    hibernate-orm:
      scripts:
        generation:
          ~: create
          create-target: ddl.sql
    flyway:
      locations: db/migration-dev

"%test":
  quarkus:
    datasource:
      devservices:
        port: 5434
    flyway:
      locations: db/migration-dev
